MODEL:
  NAME: msmt_vit32_224
  DEVICE_ID: ('0')
  DEVICE: 'cuda'
  PRETRAIN_PATH: ./pretrain/abc.pth
  BASE_MODEL: vit_base_patch32_224

INPUT:
  SIZE_TRAIN: [224, 224]
  SIZE_TEST: [224, 224]

DATASETS:
  NAMES: msmt17
  ROOT_DIR: ./data

DATALOADER:
  NUM_WORKERS: 2

SOLVER:
  OPTIMIZER_NAME: 'ADAM'
  MAX_EPOCHS: 100
  BASE_LR: 0.0003
  SEED: 1
  WEIGHT_DECAY: 0.0005
  CHECKPOINT_PATH: ./checkpoint/abc.ckpt
  RESUME_TRAINING: False
  BLOCKWISE_FINETUNE: True
  STEP_LR_SIZE: 1
  GAMMA: 1
  LR_DECAY_BLOCK: 0.8
  IMS_PER_BATCH: 32

TEST:
  IMS_PER_BATCH: 32

OUTPUT_DIR: '/content/drive/MyDrive/saved_weights'